package com.angkorteam.bank.dao.tenant.flyway;

import com.angkorteam.bank.dao.tenant.Checksum;
import com.angkorteam.jdbc.query.InsertQuery;
import com.angkorteam.metamodel.LiquibaseJavaMigration;
import org.apache.metamodel.jdbc.JdbcDataContext;
import org.apache.metamodel.schema.Table;
import org.flywaydb.core.api.migration.Context;
import org.flywaydb.core.internal.jdbc.DriverDataSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;

import javax.sql.DataSource;

public class V1__MifosPlatformSharedTenants extends LiquibaseJavaMigration {

    @Override
    public Integer getChecksum() {
        return Checksum.V1__MifosPlatformSharedTenants + getInternalChecksum("V1__mifos-platform-shared-tenants-001.xml",
                "V1__mifos-platform-shared-tenants-003.xml");
    }

    @Override
    protected void doMigrate(Context context, DataSource dataSource, NamedParameterJdbcTemplate named, JdbcDataContext dataContext) throws Exception {
        // sub change 001
        updateLiquibase("V1__mifos-platform-shared-tenants-001.xml");

        dataContext.refreshSchemas();

        // sub change 002
        DriverDataSource driver = (DriverDataSource) context.getConfiguration().getDataSource();
        String schemaName = System.getProperty("db.tenant.name");
        String url = driver.getUrl();
        String schemaServer = null;
        String schemaServerPort = null;
        url = url.substring(url.indexOf(":") + 1);
        String type = url.substring(0, url.indexOf(":"));
        url = url.substring(url.indexOf(":") + 1);
        if ("mysql".equals(type)) {
            url = url.substring(2, url.lastIndexOf("/"));
            if (url.contains(":")) {
                String temp[] = url.split(":");
                schemaServer = temp[0];
                schemaServerPort = temp[1];
            } else {
                schemaServer = url;
                schemaServerPort = "3306";
            }
        } else if ("oracle".equals(type)) {
            url = url.substring(url.indexOf("@"));
            schemaServer = url.substring(0, url.indexOf(":"));
            url = url.substring(url.indexOf(":") + 1);
            schemaServerPort = url.substring(0, url.indexOf(":"));
        }
        dataContext.refreshSchemas();
        Table tenants = dataContext.getDefaultSchema().getTableByName("tenants");
        insert_tenants(named, tenants, 1, "default", "Default Demo Tenant", schemaName, "Asia/Kolkata", schemaServer, schemaServerPort, driver.getUser(), driver.getPassword(), "1");

        // sub change 003
        updateLiquibase("V1__mifos-platform-shared-tenants-003.xml");

        // sub change 004
        dataContext.refreshSchemas();
        Table timezones = dataContext.getDefaultSchema().getTableByName("timezones");
        insert_timezones(named, timezones, 1, "AD", "Europe/Andorra", "");
        insert_timezones(named, timezones, 2, "AE", "Asia/Dubai", "");
        insert_timezones(named, timezones, 3, "AF", "Asia/Kabul", "");
        insert_timezones(named, timezones, 4, "AG", "America/Antigua", "");
        insert_timezones(named, timezones, 5, "AI", "America/Anguilla", "");
        insert_timezones(named, timezones, 6, "AL", "Europe/Tirane", "");
        insert_timezones(named, timezones, 7, "AM", "Asia/Yerevan", "");
        insert_timezones(named, timezones, 8, "AO", "Africa/Luanda", "");
        insert_timezones(named, timezones, 9, "AQ", "Antarctica/McMurdo", "McMurdo Station, Ross Island");
        insert_timezones(named, timezones, 10, "AQ", "Antarctica/South_Pole", "Amundsen-Scott Station, South Pole");
        insert_timezones(named, timezones, 11, "AQ", "Antarctica/Rothera", "Rothera Station, Adelaide Island");
        insert_timezones(named, timezones, 12, "AQ", "Antarctica/Palmer", "Palmer Station, Anvers Island");
        insert_timezones(named, timezones, 13, "AQ", "Antarctica/Mawson", "Mawson Station, Holme Bay");
        insert_timezones(named, timezones, 14, "AQ", "Antarctica/Davis", "Davis Station, Vestfold Hills");
        insert_timezones(named, timezones, 15, "AQ", "Antarctica/Casey", "Casey Station, Bailey Peninsula");
        insert_timezones(named, timezones, 16, "AQ", "Antarctica/Vostok", "Vostok Station, Lake Vostok");
        insert_timezones(named, timezones, 17, "AQ", "Antarctica/DumontDUrville", "Dumont-dUrville Station, Terre Adelie");
        insert_timezones(named, timezones, 18, "AQ", "Antarctica/Syowa", "Syowa Station, E Ongul I");
        insert_timezones(named, timezones, 19, "AQ", "Antarctica/Macquarie", "Macquarie Island Station, Macquarie Island");
        insert_timezones(named, timezones, 20, "AR", "America/Argentina/Buenos_Aires", "Buenos Aires (BA, CF)");
        insert_timezones(named, timezones, 21, "AR", "America/Argentina/Cordoba", "most locations (CB, CC, CN, ER, FM, MN, SE, SF)");
        insert_timezones(named, timezones, 22, "AR", "America/Argentina/Salta", "(SA, LP, NQ, RN)");
        insert_timezones(named, timezones, 23, "AR", "America/Argentina/Jujuy", "Jujuy (JY)");
        insert_timezones(named, timezones, 24, "AR", "America/Argentina/Tucuman", "Tucuman (TM)");
        insert_timezones(named, timezones, 25, "AR", "America/Argentina/Catamarca", "Catamarca (CT), Chubut (CH)");
        insert_timezones(named, timezones, 26, "AR", "America/Argentina/La_Rioja", "La Rioja (LR)");
        insert_timezones(named, timezones, 27, "AR", "America/Argentina/San_Juan", "San Juan (SJ)");
        insert_timezones(named, timezones, 28, "AR", "America/Argentina/Mendoza", "Mendoza (MZ)");
        insert_timezones(named, timezones, 29, "AR", "America/Argentina/San_Luis", "San Luis (SL)");
        insert_timezones(named, timezones, 30, "AR", "America/Argentina/Rio_Gallegos", "Santa Cruz (SC)");
        insert_timezones(named, timezones, 31, "AR", "America/Argentina/Ushuaia", "Tierra del Fuego (TF)");
        insert_timezones(named, timezones, 32, "AS", "Pacific/Pago_Pago", "");
        insert_timezones(named, timezones, 33, "AT", "Europe/Vienna", "");
        insert_timezones(named, timezones, 34, "AU", "Australia/Lord_Howe", "Lord Howe Island");
        insert_timezones(named, timezones, 35, "AU", "Australia/Hobart", "Tasmania - most locations");
        insert_timezones(named, timezones, 36, "AU", "Australia/Currie", "Tasmania - King Island");
        insert_timezones(named, timezones, 37, "AU", "Australia/Melbourne", "Victoria");
        insert_timezones(named, timezones, 38, "AU", "Australia/Sydney", "New South Wales - most locations");
        insert_timezones(named, timezones, 39, "AU", "Australia/Broken_Hill", "New South Wales - Yancowinna");
        insert_timezones(named, timezones, 40, "AU", "Australia/Brisbane", "Queensland - most locations");
        insert_timezones(named, timezones, 41, "AU", "Australia/Lindeman", "Queensland - Holiday Islands");
        insert_timezones(named, timezones, 42, "AU", "Australia/Adelaide", "South Australia");
        insert_timezones(named, timezones, 43, "AU", "Australia/Darwin", "Northern Territory");
        insert_timezones(named, timezones, 44, "AU", "Australia/Perth", "Western Australia - most locations");
        insert_timezones(named, timezones, 45, "AU", "Australia/Eucla", "Western Australia - Eucla area");
        insert_timezones(named, timezones, 46, "AW", "America/Aruba", "");
        insert_timezones(named, timezones, 47, "AX", "Europe/Mariehamn", "");
        insert_timezones(named, timezones, 48, "AZ", "Asia/Baku", "");
        insert_timezones(named, timezones, 49, "BA", "Europe/Sarajevo", "");
        insert_timezones(named, timezones, 50, "BB", "America/Barbados", "");
        insert_timezones(named, timezones, 51, "BD", "Asia/Dhaka", "");
        insert_timezones(named, timezones, 52, "BE", "Europe/Brussels", "");
        insert_timezones(named, timezones, 53, "BF", "Africa/Ouagadougou", "");
        insert_timezones(named, timezones, 54, "BG", "Europe/Sofia", "");
        insert_timezones(named, timezones, 55, "BH", "Asia/Bahrain", "");
        insert_timezones(named, timezones, 56, "BI", "Africa/Bujumbura", "");
        insert_timezones(named, timezones, 57, "BJ", "Africa/Porto-Novo", "");
        insert_timezones(named, timezones, 58, "BL", "America/St_Barthelemy", "");
        insert_timezones(named, timezones, 59, "BM", "Atlantic/Bermuda", "");
        insert_timezones(named, timezones, 60, "BN", "Asia/Brunei", "");
        insert_timezones(named, timezones, 61, "BO", "America/La_Paz", "");
        insert_timezones(named, timezones, 62, "BQ", "America/Kralendijk", "");
        insert_timezones(named, timezones, 63, "BR", "America/Noronha", "Atlantic islands");
        insert_timezones(named, timezones, 64, "BR", "America/Belem", "Amapa, E Para");
        insert_timezones(named, timezones, 65, "BR", "America/Fortaleza", "NE Brazil (MA, PI, CE, RN, PB)");
        insert_timezones(named, timezones, 66, "BR", "America/Recife", "Pernambuco");
        insert_timezones(named, timezones, 67, "BR", "America/Araguaina", "Tocantins");
        insert_timezones(named, timezones, 68, "BR", "America/Maceio", "Alagoas, Sergipe");
        insert_timezones(named, timezones, 69, "BR", "America/Bahia", "Bahia");
        insert_timezones(named, timezones, 70, "BR", "America/Sao_Paulo", "S & SE Brazil (GO, DF, MG, ES, RJ, SP, PR, SC, RS)");
        insert_timezones(named, timezones, 71, "BR", "America/Campo_Grande", "Mato Grosso do Sul");
        insert_timezones(named, timezones, 72, "BR", "America/Cuiaba", "Mato Grosso");
        insert_timezones(named, timezones, 73, "BR", "America/Santarem", "W Para");
        insert_timezones(named, timezones, 74, "BR", "America/Porto_Velho", "Rondonia");
        insert_timezones(named, timezones, 75, "BR", "America/Boa_Vista", "Roraima");
        insert_timezones(named, timezones, 76, "BR", "America/Manaus", "E Amazonas");
        insert_timezones(named, timezones, 77, "BR", "America/Eirunepe", "W Amazonas");
        insert_timezones(named, timezones, 78, "BR", "America/Rio_Branco", "Acre");
        insert_timezones(named, timezones, 79, "BS", "America/Nassau", "");
        insert_timezones(named, timezones, 80, "BT", "Asia/Thimphu", "");
        insert_timezones(named, timezones, 81, "BW", "Africa/Gaborone", "");
        insert_timezones(named, timezones, 82, "BY", "Europe/Minsk", "");
        insert_timezones(named, timezones, 83, "BZ", "America/Belize", "");
        insert_timezones(named, timezones, 84, "CA", "America/St_Johns", "Newfoundland Time, including SE Labrador");
        insert_timezones(named, timezones, 85, "CA", "America/Halifax", "Atlantic Time - Nova Scotia (most places), PEI");
        insert_timezones(named, timezones, 86, "CA", "America/Glace_Bay", "Atlantic Time - Nova Scotia - places that did not observe DST 1966-1971");
        insert_timezones(named, timezones, 87, "CA", "America/Moncton", "Atlantic Time - New Brunswick");
        insert_timezones(named, timezones, 88, "CA", "America/Goose_Bay", "Atlantic Time - Labrador - most locations");
        insert_timezones(named, timezones, 89, "CA", "America/Blanc-Sablon", "Atlantic Standard Time - Quebec - Lower North Shore");
        insert_timezones(named, timezones, 90, "CA", "America/Montreal", "Eastern Time - Quebec - most locations");
        insert_timezones(named, timezones, 91, "CA", "America/Toronto", "Eastern Time - Ontario - most locations");
        insert_timezones(named, timezones, 92, "CA", "America/Nipigon", "Eastern Time - Ontario & Quebec - places that did not observe DST 1967-1973");
        insert_timezones(named, timezones, 93, "CA", "America/Thunder_Bay", "Eastern Time - Thunder Bay, Ontario");
        insert_timezones(named, timezones, 94, "CA", "America/Iqaluit", "Eastern Time - east Nunavut - most locations");
        insert_timezones(named, timezones, 95, "CA", "America/Pangnirtung", "Eastern Time - Pangnirtung, Nunavut");
        insert_timezones(named, timezones, 96, "CA", "America/Resolute", "Central Standard Time - Resolute, Nunavut");
        insert_timezones(named, timezones, 97, "CA", "America/Atikokan", "Eastern Standard Time - Atikokan, Ontario and Southampton I, Nunavut");
        insert_timezones(named, timezones, 98, "CA", "America/Rankin_Inlet", "Central Time - central Nunavut");
        insert_timezones(named, timezones, 99, "CA", "America/Winnipeg", "Central Time - Manitoba & west Ontario");
        insert_timezones(named, timezones, 100, "CA", "America/Rainy_River", "Central Time - Rainy River & Fort Frances, Ontario");
        insert_timezones(named, timezones, 101, "CA", "America/Regina", "Central Standard Time - Saskatchewan - most locations");
        insert_timezones(named, timezones, 102, "CA", "America/Swift_Current", "Central Standard Time - Saskatchewan - midwest");
        insert_timezones(named, timezones, 103, "CA", "America/Edmonton", "Mountain Time - Alberta, east British Columbia & west Saskatchewan");
        insert_timezones(named, timezones, 104, "CA", "America/Cambridge_Bay", "Mountain Time - west Nunavut");
        insert_timezones(named, timezones, 105, "CA", "America/Yellowknife", "Mountain Time - central Northwest Territories");
        insert_timezones(named, timezones, 106, "CA", "America/Inuvik", "Mountain Time - west Northwest Territories");
        insert_timezones(named, timezones, 107, "CA", "America/Creston", "Mountain Standard Time - Creston, British Columbia");
        insert_timezones(named, timezones, 108, "CA", "America/Dawson_Creek", "Mountain Standard Time - Dawson Creek & Fort Saint John, British Columbia");
        insert_timezones(named, timezones, 109, "CA", "America/Vancouver", "Pacific Time - west British Columbia");
        insert_timezones(named, timezones, 110, "CA", "America/Whitehorse", "Pacific Time - south Yukon");
        insert_timezones(named, timezones, 111, "CA", "America/Dawson", "Pacific Time - north Yukon");
        insert_timezones(named, timezones, 112, "CC", "Indian/Cocos", "");
        insert_timezones(named, timezones, 113, "CD", "Africa/Kinshasa", "west Dem. Rep. of Congo");
        insert_timezones(named, timezones, 114, "CD", "Africa/Lubumbashi", "east Dem. Rep. of Congo");
        insert_timezones(named, timezones, 115, "CF", "Africa/Bangui", "");
        insert_timezones(named, timezones, 116, "CG", "Africa/Brazzaville", "");
        insert_timezones(named, timezones, 117, "CH", "Europe/Zurich", "");
        insert_timezones(named, timezones, 118, "CI", "Africa/Abidjan", "");
        insert_timezones(named, timezones, 119, "CK", "Pacific/Rarotonga", "");
        insert_timezones(named, timezones, 120, "CL", "America/Santiago", "most locations");
        insert_timezones(named, timezones, 121, "CL", "Pacific/Easter", "Easter Island & Sala y Gomez");
        insert_timezones(named, timezones, 122, "CM", "Africa/Douala", "");
        insert_timezones(named, timezones, 123, "CN", "Asia/Shanghai", "east China - Beijing, Guangdong, Shanghai, etc.");
        insert_timezones(named, timezones, 124, "CN", "Asia/Harbin", "Heilongjiang (except Mohe), Jilin");
        insert_timezones(named, timezones, 125, "CN", "Asia/Chongqing", "central China - Sichuan, Yunnan, Guangxi, Shaanxi, Guizhou, etc.");
        insert_timezones(named, timezones, 126, "CN", "Asia/Urumqi", "most of Tibet & Xinjiang");
        insert_timezones(named, timezones, 127, "CN", "Asia/Kashgar", "west Tibet & Xinjiang");
        insert_timezones(named, timezones, 128, "CO", "America/Bogota", "");
        insert_timezones(named, timezones, 129, "CR", "America/Costa_Rica", "");
        insert_timezones(named, timezones, 130, "CU", "America/Havana", "");
        insert_timezones(named, timezones, 131, "CV", "Atlantic/Cape_Verde", "");
        insert_timezones(named, timezones, 132, "CW", "America/Curacao", "");
        insert_timezones(named, timezones, 133, "CX", "Indian/Christmas", "");
        insert_timezones(named, timezones, 134, "CY", "Asia/Nicosia", "");
        insert_timezones(named, timezones, 135, "CZ", "Europe/Prague", "");
        insert_timezones(named, timezones, 136, "DE", "Europe/Berlin", "");
        insert_timezones(named, timezones, 137, "DJ", "Africa/Djibouti", "");
        insert_timezones(named, timezones, 138, "DK", "Europe/Copenhagen", "");
        insert_timezones(named, timezones, 139, "DM", "America/Dominica", "");
        insert_timezones(named, timezones, 140, "DO", "America/Santo_Domingo", "");
        insert_timezones(named, timezones, 141, "DZ", "Africa/Algiers", "");
        insert_timezones(named, timezones, 142, "EC", "America/Guayaquil", "mainland");
        insert_timezones(named, timezones, 143, "EC", "Pacific/Galapagos", "Galapagos Islands");
        insert_timezones(named, timezones, 144, "EE", "Europe/Tallinn", "");
        insert_timezones(named, timezones, 145, "EG", "Africa/Cairo", "");
        insert_timezones(named, timezones, 146, "EH", "Africa/El_Aaiun", "");
        insert_timezones(named, timezones, 147, "ER", "Africa/Asmara", "");
        insert_timezones(named, timezones, 148, "ES", "Europe/Madrid", "mainland");
        insert_timezones(named, timezones, 149, "ES", "Africa/Ceuta", "Ceuta & Melilla");
        insert_timezones(named, timezones, 150, "ES", "Atlantic/Canary", "Canary Islands");
        insert_timezones(named, timezones, 151, "ET", "Africa/Addis_Ababa", "");
        insert_timezones(named, timezones, 152, "FI", "Europe/Helsinki", "");
        insert_timezones(named, timezones, 153, "FJ", "Pacific/Fiji", "");
        insert_timezones(named, timezones, 154, "FK", "Atlantic/Stanley", "");
        insert_timezones(named, timezones, 155, "FM", "Pacific/Chuuk", "Chuuk (Truk) and Yap");
        insert_timezones(named, timezones, 156, "FM", "Pacific/Pohnpei", "Pohnpei (Ponape)");
        insert_timezones(named, timezones, 157, "FM", "Pacific/Kosrae", "Kosrae");
        insert_timezones(named, timezones, 158, "FO", "Atlantic/Faroe", "");
        insert_timezones(named, timezones, 159, "FR", "Europe/Paris", "");
        insert_timezones(named, timezones, 160, "GA", "Africa/Libreville", "");
        insert_timezones(named, timezones, 161, "GB", "Europe/London", "");
        insert_timezones(named, timezones, 162, "GD", "America/Grenada", "");
        insert_timezones(named, timezones, 163, "GE", "Asia/Tbilisi", "");
        insert_timezones(named, timezones, 164, "GF", "America/Cayenne", "");
        insert_timezones(named, timezones, 165, "GG", "Europe/Guernsey", "");
        insert_timezones(named, timezones, 166, "GH", "Africa/Accra", "");
        insert_timezones(named, timezones, 167, "GI", "Europe/Gibraltar", "");
        insert_timezones(named, timezones, 168, "GL", "America/Godthab", "most locations");
        insert_timezones(named, timezones, 169, "GL", "America/Danmarkshavn", "east coast, north of Scoresbysund");
        insert_timezones(named, timezones, 170, "GL", "America/Scoresbysund", "Scoresbysund / Ittoqqortoormiit");
        insert_timezones(named, timezones, 171, "GL", "America/Thule", "Thule / Pituffik");
        insert_timezones(named, timezones, 172, "GM", "Africa/Banjul", "");
        insert_timezones(named, timezones, 173, "GN", "Africa/Conakry", "");
        insert_timezones(named, timezones, 174, "GP", "America/Guadeloupe", "");
        insert_timezones(named, timezones, 175, "GQ", "Africa/Malabo", "");
        insert_timezones(named, timezones, 176, "GR", "Europe/Athens", "");
        insert_timezones(named, timezones, 177, "GS", "Atlantic/South_Georgia", "");
        insert_timezones(named, timezones, 178, "GT", "America/Guatemala", "");
        insert_timezones(named, timezones, 179, "GU", "Pacific/Guam", "");
        insert_timezones(named, timezones, 180, "GW", "Africa/Bissau", "");
        insert_timezones(named, timezones, 181, "GY", "America/Guyana", "");
        insert_timezones(named, timezones, 182, "HK", "Asia/Hong_Kong", "");
        insert_timezones(named, timezones, 183, "HN", "America/Tegucigalpa", "");
        insert_timezones(named, timezones, 184, "HR", "Europe/Zagreb", "");
        insert_timezones(named, timezones, 185, "HT", "America/Port-au-Prince", "");
        insert_timezones(named, timezones, 186, "HU", "Europe/Budapest", "");
        insert_timezones(named, timezones, 187, "ID", "Asia/Jakarta", "Java & Sumatra");
        insert_timezones(named, timezones, 188, "ID", "Asia/Pontianak", "west & central Borneo");
        insert_timezones(named, timezones, 189, "ID", "Asia/Makassar", "east & south Borneo, Sulawesi (Celebes), Bali, Nusa Tengarra, west Timor");
        insert_timezones(named, timezones, 190, "ID", "Asia/Jayapura", "west New Guinea (Irian Jaya) & Malukus (Moluccas)");
        insert_timezones(named, timezones, 191, "IE", "Europe/Dublin", "");
        insert_timezones(named, timezones, 192, "IL", "Asia/Jerusalem", "");
        insert_timezones(named, timezones, 193, "IM", "Europe/Isle_of_Man", "");
        insert_timezones(named, timezones, 194, "IN", "Asia/Kolkata", "");
        insert_timezones(named, timezones, 195, "IO", "Indian/Chagos", "");
        insert_timezones(named, timezones, 196, "IQ", "Asia/Baghdad", "");
        insert_timezones(named, timezones, 197, "IR", "Asia/Tehran", "");
        insert_timezones(named, timezones, 198, "IS", "Atlantic/Reykjavik", "");
        insert_timezones(named, timezones, 199, "IT", "Europe/Rome", "");
        insert_timezones(named, timezones, 200, "JE", "Europe/Jersey", "");
        insert_timezones(named, timezones, 201, "JM", "America/Jamaica", "");
        insert_timezones(named, timezones, 202, "JO", "Asia/Amman", "");
        insert_timezones(named, timezones, 203, "JP", "Asia/Tokyo", "");
        insert_timezones(named, timezones, 204, "KE", "Africa/Nairobi", "");
        insert_timezones(named, timezones, 205, "KG", "Asia/Bishkek", "");
        insert_timezones(named, timezones, 206, "KH", "Asia/Phnom_Penh", "");
        insert_timezones(named, timezones, 207, "KI", "Pacific/Tarawa", "Gilbert Islands");
        insert_timezones(named, timezones, 208, "KI", "Pacific/Enderbury", "Phoenix Islands");
        insert_timezones(named, timezones, 209, "KI", "Pacific/Kiritimati", "Line Islands");
        insert_timezones(named, timezones, 210, "KM", "Indian/Comoro", "");
        insert_timezones(named, timezones, 211, "KN", "America/St_Kitts", "");
        insert_timezones(named, timezones, 212, "KP", "Asia/Pyongyang", "");
        insert_timezones(named, timezones, 213, "KR", "Asia/Seoul", "");
        insert_timezones(named, timezones, 214, "KW", "Asia/Kuwait", "");
        insert_timezones(named, timezones, 215, "KY", "America/Cayman", "");
        insert_timezones(named, timezones, 216, "KZ", "Asia/Almaty", "most locations");
        insert_timezones(named, timezones, 217, "KZ", "Asia/Qyzylorda", "Qyzylorda (Kyzylorda, Kzyl-Orda)");
        insert_timezones(named, timezones, 218, "KZ", "Asia/Aqtobe", "Aqtobe (Aktobe)");
        insert_timezones(named, timezones, 219, "KZ", "Asia/Aqtau", "Atyrau (Atirau, Guryev), Mangghystau (Mankistau)");
        insert_timezones(named, timezones, 220, "KZ", "Asia/Oral", "West Kazakhstan");
        insert_timezones(named, timezones, 221, "LA", "Asia/Vientiane", "");
        insert_timezones(named, timezones, 222, "LB", "Asia/Beirut", "");
        insert_timezones(named, timezones, 223, "LC", "America/St_Lucia", "");
        insert_timezones(named, timezones, 224, "LI", "Europe/Vaduz", "");
        insert_timezones(named, timezones, 225, "LK", "Asia/Colombo", "");
        insert_timezones(named, timezones, 226, "LR", "Africa/Monrovia", "");
        insert_timezones(named, timezones, 227, "LS", "Africa/Maseru", "");
        insert_timezones(named, timezones, 228, "LT", "Europe/Vilnius", "");
        insert_timezones(named, timezones, 229, "LU", "Europe/Luxembourg", "");
        insert_timezones(named, timezones, 230, "LV", "Europe/Riga", "");
        insert_timezones(named, timezones, 231, "LY", "Africa/Tripoli", "");
        insert_timezones(named, timezones, 232, "MA", "Africa/Casablanca", "");
        insert_timezones(named, timezones, 233, "MC", "Europe/Monaco", "");
        insert_timezones(named, timezones, 234, "MD", "Europe/Chisinau", "");
        insert_timezones(named, timezones, 235, "ME", "Europe/Podgorica", "");
        insert_timezones(named, timezones, 236, "MF", "America/Marigot", "");
        insert_timezones(named, timezones, 237, "MG", "Indian/Antananarivo", "");
        insert_timezones(named, timezones, 238, "MH", "Pacific/Majuro", "most locations");
        insert_timezones(named, timezones, 239, "MH", "Pacific/Kwajalein", "Kwajalein");
        insert_timezones(named, timezones, 240, "MK", "Europe/Skopje", "");
        insert_timezones(named, timezones, 241, "ML", "Africa/Bamako", "");
        insert_timezones(named, timezones, 242, "MM", "Asia/Rangoon", "");
        insert_timezones(named, timezones, 243, "MN", "Asia/Ulaanbaatar", "most locations");
        insert_timezones(named, timezones, 244, "MN", "Asia/Hovd", "Bayan-Olgiy, Govi-Altai, Hovd, Uvs, Zavkhan");
        insert_timezones(named, timezones, 245, "MN", "Asia/Choibalsan", "Dornod, Sukhbaatar");
        insert_timezones(named, timezones, 246, "MO", "Asia/Macau", "");
        insert_timezones(named, timezones, 247, "MP", "Pacific/Saipan", "");
        insert_timezones(named, timezones, 248, "MQ", "America/Martinique", "");
        insert_timezones(named, timezones, 249, "MR", "Africa/Nouakchott", "");
        insert_timezones(named, timezones, 250, "MS", "America/Montserrat", "");
        insert_timezones(named, timezones, 251, "MT", "Europe/Malta", "");
        insert_timezones(named, timezones, 252, "MU", "Indian/Mauritius", "");
        insert_timezones(named, timezones, 253, "MV", "Indian/Maldives", "");
        insert_timezones(named, timezones, 254, "MW", "Africa/Blantyre", "");
        insert_timezones(named, timezones, 255, "MX", "America/Mexico_City", "Central Time - most locations");
        insert_timezones(named, timezones, 256, "MX", "America/Cancun", "Central Time - Quintana Roo");
        insert_timezones(named, timezones, 257, "MX", "America/Merida", "Central Time - Campeche, Yucatan");
        insert_timezones(named, timezones, 258, "MX", "America/Monterrey", "Mexican Central Time - Coahuila, Durango, Nuevo Leon, Tamaulipas away from US border");
        insert_timezones(named, timezones, 259, "MX", "America/Matamoros", "US Central Time - Coahuila, Durango, Nuevo Leon, Tamaulipas near US border");
        insert_timezones(named, timezones, 260, "MX", "America/Mazatlan", "Mountain Time - S Baja, Nayarit, Sinaloa");
        insert_timezones(named, timezones, 261, "MX", "America/Chihuahua", "Mexican Mountain Time - Chihuahua away from US border");
        insert_timezones(named, timezones, 262, "MX", "America/Ojinaga", "US Mountain Time - Chihuahua near US border");
        insert_timezones(named, timezones, 263, "MX", "America/Hermosillo", "Mountain Standard Time - Sonora");
        insert_timezones(named, timezones, 264, "MX", "America/Tijuana", "US Pacific Time - Baja California near US border");
        insert_timezones(named, timezones, 265, "MX", "America/Santa_Isabel", "Mexican Pacific Time - Baja California away from US border");
        insert_timezones(named, timezones, 266, "MX", "America/Bahia_Banderas", "Mexican Central Time - Bahia de Banderas");
        insert_timezones(named, timezones, 267, "MY", "Asia/Kuala_Lumpur", "peninsular Malaysia");
        insert_timezones(named, timezones, 268, "MY", "Asia/Kuching", "Sabah & Sarawak");
        insert_timezones(named, timezones, 269, "MZ", "Africa/Maputo", "");
        insert_timezones(named, timezones, 270, "NA", "Africa/Windhoek", "");
        insert_timezones(named, timezones, 271, "NC", "Pacific/Noumea", "");
        insert_timezones(named, timezones, 272, "NE", "Africa/Niamey", "");
        insert_timezones(named, timezones, 273, "NF", "Pacific/Norfolk", "");
        insert_timezones(named, timezones, 274, "NG", "Africa/Lagos", "");
        insert_timezones(named, timezones, 275, "NI", "America/Managua", "");
        insert_timezones(named, timezones, 276, "NL", "Europe/Amsterdam", "");
        insert_timezones(named, timezones, 277, "NO", "Europe/Oslo", "");
        insert_timezones(named, timezones, 278, "NP", "Asia/Kathmandu", "");
        insert_timezones(named, timezones, 279, "NR", "Pacific/Nauru", "");
        insert_timezones(named, timezones, 280, "NU", "Pacific/Niue", "");
        insert_timezones(named, timezones, 281, "NZ", "Pacific/Auckland", "most locations");
        insert_timezones(named, timezones, 282, "NZ", "Pacific/Chatham", "Chatham Islands");
        insert_timezones(named, timezones, 283, "OM", "Asia/Muscat", "");
        insert_timezones(named, timezones, 284, "PA", "America/Panama", "");
        insert_timezones(named, timezones, 285, "PE", "America/Lima", "");
        insert_timezones(named, timezones, 286, "PF", "Pacific/Tahiti", "Society Islands");
        insert_timezones(named, timezones, 287, "PF", "Pacific/Marquesas", "Marquesas Islands");
        insert_timezones(named, timezones, 288, "PF", "Pacific/Gambier", "Gambier Islands");
        insert_timezones(named, timezones, 289, "PG", "Pacific/Port_Moresby", "");
        insert_timezones(named, timezones, 290, "PH", "Asia/Manila", "");
        insert_timezones(named, timezones, 291, "PK", "Asia/Karachi", "");
        insert_timezones(named, timezones, 292, "PL", "Europe/Warsaw", "");
        insert_timezones(named, timezones, 293, "PM", "America/Miquelon", "");
        insert_timezones(named, timezones, 294, "PN", "Pacific/Pitcairn", "");
        insert_timezones(named, timezones, 295, "PR", "America/Puerto_Rico", "");
        insert_timezones(named, timezones, 296, "PS", "Asia/Gaza", "Gaza Strip");
        insert_timezones(named, timezones, 297, "PS", "Asia/Hebron", "West Bank");
        insert_timezones(named, timezones, 298, "PT", "Europe/Lisbon", "mainland");
        insert_timezones(named, timezones, 299, "PT", "Atlantic/Madeira", "Madeira Islands");
        insert_timezones(named, timezones, 300, "PT", "Atlantic/Azores", "Azores");
        insert_timezones(named, timezones, 301, "PW", "Pacific/Palau", "");
        insert_timezones(named, timezones, 302, "PY", "America/Asuncion", "");
        insert_timezones(named, timezones, 303, "QA", "Asia/Qatar", "");
        insert_timezones(named, timezones, 304, "RE", "Indian/Reunion", "");
        insert_timezones(named, timezones, 305, "RO", "Europe/Bucharest", "");
        insert_timezones(named, timezones, 306, "RS", "Europe/Belgrade", "");
        insert_timezones(named, timezones, 307, "RU", "Europe/Kaliningrad", "Moscow-01 - Kaliningrad");
        insert_timezones(named, timezones, 308, "RU", "Europe/Moscow", "Moscow+00 - west Russia");
        insert_timezones(named, timezones, 309, "RU", "Europe/Volgograd", "Moscow+00 - Caspian Sea");
        insert_timezones(named, timezones, 310, "RU", "Europe/Samara", "Moscow+00 - Samara, Udmurtia");
        insert_timezones(named, timezones, 311, "RU", "Asia/Yekaterinburg", "Moscow+02 - Urals");
        insert_timezones(named, timezones, 312, "RU", "Asia/Omsk", "Moscow+03 - west Siberia");
        insert_timezones(named, timezones, 313, "RU", "Asia/Novosibirsk", "Moscow+03 - Novosibirsk");
        insert_timezones(named, timezones, 314, "RU", "Asia/Novokuznetsk", "Moscow+03 - Novokuznetsk");
        insert_timezones(named, timezones, 315, "RU", "Asia/Krasnoyarsk", "Moscow+04 - Yenisei River");
        insert_timezones(named, timezones, 316, "RU", "Asia/Irkutsk", "Moscow+05 - Lake Baikal");
        insert_timezones(named, timezones, 317, "RU", "Asia/Yakutsk", "Moscow+06 - Lena River");
        insert_timezones(named, timezones, 318, "RU", "Asia/Vladivostok", "Moscow+07 - Amur River");
        insert_timezones(named, timezones, 319, "RU", "Asia/Sakhalin", "Moscow+07 - Sakhalin Island");
        insert_timezones(named, timezones, 320, "RU", "Asia/Magadan", "Moscow+08 - Magadan");
        insert_timezones(named, timezones, 321, "RU", "Asia/Kamchatka", "Moscow+08 - Kamchatka");
        insert_timezones(named, timezones, 322, "RU", "Asia/Anadyr", "Moscow+08 - Bering Sea");
        insert_timezones(named, timezones, 323, "RW", "Africa/Kigali", "");
        insert_timezones(named, timezones, 324, "SA", "Asia/Riyadh", "");
        insert_timezones(named, timezones, 325, "SB", "Pacific/Guadalcanal", "");
        insert_timezones(named, timezones, 326, "SC", "Indian/Mahe", "");
        insert_timezones(named, timezones, 327, "SD", "Africa/Khartoum", "");
        insert_timezones(named, timezones, 328, "SE", "Europe/Stockholm", "");
        insert_timezones(named, timezones, 329, "SG", "Asia/Singapore", "");
        insert_timezones(named, timezones, 330, "SH", "Atlantic/St_Helena", "");
        insert_timezones(named, timezones, 331, "SI", "Europe/Ljubljana", "");
        insert_timezones(named, timezones, 332, "SJ", "Arctic/Longyearbyen", "");
        insert_timezones(named, timezones, 333, "SK", "Europe/Bratislava", "");
        insert_timezones(named, timezones, 334, "SL", "Africa/Freetown", "");
        insert_timezones(named, timezones, 335, "SM", "Europe/San_Marino", "");
        insert_timezones(named, timezones, 336, "SN", "Africa/Dakar", "");
        insert_timezones(named, timezones, 337, "SO", "Africa/Mogadishu", "");
        insert_timezones(named, timezones, 338, "SR", "America/Paramaribo", "");
        insert_timezones(named, timezones, 339, "SS", "Africa/Juba", "");
        insert_timezones(named, timezones, 340, "ST", "Africa/Sao_Tome", "");
        insert_timezones(named, timezones, 341, "SV", "America/El_Salvador", "");
        insert_timezones(named, timezones, 342, "SX", "America/Lower_Princes", "");
        insert_timezones(named, timezones, 343, "SY", "Asia/Damascus", "");
        insert_timezones(named, timezones, 344, "SZ", "Africa/Mbabane", "");
        insert_timezones(named, timezones, 345, "TC", "America/Grand_Turk", "");
        insert_timezones(named, timezones, 346, "TD", "Africa/Ndjamena", "");
        insert_timezones(named, timezones, 347, "TF", "Indian/Kerguelen", "");
        insert_timezones(named, timezones, 348, "TG", "Africa/Lome", "");
        insert_timezones(named, timezones, 349, "TH", "Asia/Bangkok", "");
        insert_timezones(named, timezones, 350, "TJ", "Asia/Dushanbe", "");
        insert_timezones(named, timezones, 351, "TK", "Pacific/Fakaofo", "");
        insert_timezones(named, timezones, 352, "TL", "Asia/Dili", "");
        insert_timezones(named, timezones, 353, "TM", "Asia/Ashgabat", "");
        insert_timezones(named, timezones, 354, "TN", "Africa/Tunis", "");
        insert_timezones(named, timezones, 355, "TO", "Pacific/Tongatapu", "");
        insert_timezones(named, timezones, 356, "TR", "Europe/Istanbul", "");
        insert_timezones(named, timezones, 357, "TT", "America/Port_of_Spain", "");
        insert_timezones(named, timezones, 358, "TV", "Pacific/Funafuti", "");
        insert_timezones(named, timezones, 359, "TW", "Asia/Taipei", "");
        insert_timezones(named, timezones, 360, "TZ", "Africa/Dar_es_Salaam", "");
        insert_timezones(named, timezones, 361, "UA", "Europe/Kiev", "most locations");
        insert_timezones(named, timezones, 362, "UA", "Europe/Uzhgorod", "Ruthenia");
        insert_timezones(named, timezones, 363, "UA", "Europe/Zaporozhye", "Zaporozhye, E Lugansk / Zaporizhia, E Luhansk");
        insert_timezones(named, timezones, 364, "UA", "Europe/Simferopol", "central Crimea");
        insert_timezones(named, timezones, 365, "UG", "Africa/Kampala", "");
        insert_timezones(named, timezones, 366, "UM", "Pacific/Johnston", "Johnston Atoll");
        insert_timezones(named, timezones, 367, "UM", "Pacific/Midway", "Midway Islands");
        insert_timezones(named, timezones, 368, "UM", "Pacific/Wake", "Wake Island");
        insert_timezones(named, timezones, 369, "US", "America/New_York", "Eastern Time");
        insert_timezones(named, timezones, 370, "US", "America/Detroit", "Eastern Time - Michigan - most locations");
        insert_timezones(named, timezones, 371, "US", "America/Kentucky/Louisville", "Eastern Time - Kentucky - Louisville area");
        insert_timezones(named, timezones, 372, "US", "America/Kentucky/Monticello", "Eastern Time - Kentucky - Wayne County");
        insert_timezones(named, timezones, 373, "US", "America/Indiana/Indianapolis", "Eastern Time - Indiana - most locations");
        insert_timezones(named, timezones, 374, "US", "America/Indiana/Vincennes", "Eastern Time - Indiana - Daviess, Dubois, Knox & Martin Counties");
        insert_timezones(named, timezones, 375, "US", "America/Indiana/Winamac", "Eastern Time - Indiana - Pulaski County");
        insert_timezones(named, timezones, 376, "US", "America/Indiana/Marengo", "Eastern Time - Indiana - Crawford County");
        insert_timezones(named, timezones, 377, "US", "America/Indiana/Petersburg", "Eastern Time - Indiana - Pike County");
        insert_timezones(named, timezones, 378, "US", "America/Indiana/Vevay", "Eastern Time - Indiana - Switzerland County");
        insert_timezones(named, timezones, 379, "US", "America/Chicago", "Central Time");
        insert_timezones(named, timezones, 380, "US", "America/Indiana/Tell_City", "Central Time - Indiana - Perry County");
        insert_timezones(named, timezones, 381, "US", "America/Indiana/Knox", "Central Time - Indiana - Starke County");
        insert_timezones(named, timezones, 382, "US", "America/Menominee", "Central Time - Michigan - Dickinson, Gogebic, Iron & Menominee Counties");
        insert_timezones(named, timezones, 383, "US", "America/North_Dakota/Center", "Central Time - North Dakota - Oliver County");
        insert_timezones(named, timezones, 384, "US", "America/North_Dakota/New_Salem", "Central Time - North Dakota - Morton County (except Mandan area)");
        insert_timezones(named, timezones, 385, "US", "America/North_Dakota/Beulah", "Central Time - North Dakota - Mercer County");
        insert_timezones(named, timezones, 386, "US", "America/Denver", "Mountain Time");
        insert_timezones(named, timezones, 387, "US", "America/Boise", "Mountain Time - south Idaho & east Oregon");
        insert_timezones(named, timezones, 388, "US", "America/Shiprock", "Mountain Time - Navajo");
        insert_timezones(named, timezones, 389, "US", "America/Phoenix", "Mountain Standard Time - Arizona");
        insert_timezones(named, timezones, 390, "US", "America/Los_Angeles", "Pacific Time");
        insert_timezones(named, timezones, 391, "US", "America/Anchorage", "Alaska Time");
        insert_timezones(named, timezones, 392, "US", "America/Juneau", "Alaska Time - Alaska panhandle");
        insert_timezones(named, timezones, 393, "US", "America/Sitka", "Alaska Time - southeast Alaska panhandle");
        insert_timezones(named, timezones, 394, "US", "America/Yakutat", "Alaska Time - Alaska panhandle neck");
        insert_timezones(named, timezones, 395, "US", "America/Nome", "Alaska Time - west Alaska");
        insert_timezones(named, timezones, 396, "US", "America/Adak", "Aleutian Islands");
        insert_timezones(named, timezones, 397, "US", "America/Metlakatla", "Metlakatla Time - Annette Island");
        insert_timezones(named, timezones, 398, "US", "Pacific/Honolulu", "Hawaii");
        insert_timezones(named, timezones, 399, "UY", "America/Montevideo", "");
        insert_timezones(named, timezones, 400, "UZ", "Asia/Samarkand", "west Uzbekistan");
        insert_timezones(named, timezones, 401, "UZ", "Asia/Tashkent", "east Uzbekistan");
        insert_timezones(named, timezones, 402, "VA", "Europe/Vatican", "");
        insert_timezones(named, timezones, 403, "VC", "America/St_Vincent", "");
        insert_timezones(named, timezones, 404, "VE", "America/Caracas", "");
        insert_timezones(named, timezones, 405, "VG", "America/Tortola", "");
        insert_timezones(named, timezones, 406, "VI", "America/St_Thomas", "");
        insert_timezones(named, timezones, 407, "VN", "Asia/Ho_Chi_Minh", "");
        insert_timezones(named, timezones, 408, "VU", "Pacific/Efate", "");
        insert_timezones(named, timezones, 409, "WF", "Pacific/Wallis", "");
        insert_timezones(named, timezones, 410, "WS", "Pacific/Apia", "");
        insert_timezones(named, timezones, 411, "YE", "Asia/Aden", "");
        insert_timezones(named, timezones, 412, "YT", "Indian/Mayotte", "");
        insert_timezones(named, timezones, 413, "ZA", "Africa/Johannesburg", "");
        insert_timezones(named, timezones, 414, "ZM", "Africa/Lusaka", "");
        insert_timezones(named, timezones, 415, "ZW", "Africa/Harare", "");
    }

    protected static void insert_tenants(NamedParameterJdbcTemplate named, Table table, long id, String identifier, String name, String schema_name, String timezone_id, String schema_server, String schema_server_port, String schema_username, String schema_password, String auto_update) {
        InsertQuery insertQuery = new InsertQuery(table.getName());
        insertQuery.addValue(table.getColumnByName("id").getName() + " = :id", id);
        insertQuery.addValue(table.getColumnByName("identifier").getName() + " = :identifier", identifier);
        insertQuery.addValue(table.getColumnByName("name").getName() + " = :name", name);
        insertQuery.addValue(table.getColumnByName("schema_name").getName() + " = :schema_name", schema_name);
        insertQuery.addValue(table.getColumnByName("timezone_id").getName() + " = :timezone_id", timezone_id);
        insertQuery.addValue(table.getColumnByName("schema_server").getName() + " = :schema_server", schema_server);
        insertQuery.addValue(table.getColumnByName("schema_server_port").getName() + " = :schema_server_port", schema_server_port);
        insertQuery.addValue(table.getColumnByName("schema_username").getName() + " = :schema_username", schema_username);
        insertQuery.addValue(table.getColumnByName("schema_password").getName() + " = :schema_password", schema_password);
        insertQuery.addValue(table.getColumnByName("auto_update").getName() + " = :auto_update", auto_update);
        named.update(insertQuery.toSQL(), insertQuery.toParam());
    }

    protected static void insert_timezones(NamedParameterJdbcTemplate named, Table table, long id, String code, String name, String comment) {
        InsertQuery insertQuery = new InsertQuery(table.getName());
        insertQuery.addValue(table.getColumnByName("id").getName() + " = :id", id);
        insertQuery.addValue(table.getColumnByName("code").getName() + " = :code", code);
        insertQuery.addValue(table.getColumnByName("name").getName() + " = :name", name);
        insertQuery.addValue(table.getColumnByName("comment").getName() + " = :comment", comment);
        named.update(insertQuery.toSQL(), insertQuery.toParam());
    }

}